//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CtrDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004000000030500	ASSJ	スーパーストリートファイターIV 3D EDITION
        ///0004000000030B00	ADAJ	nintendogs + cats 柴 &amp; Newフレンズ
        ///0004000000031000	ADBJ	nintendogs + cats フレンチ･ブル &amp; Newフレンズ
        ///0004000000031500	ADCJ	nintendogs + cats トイ･プードル &amp; Newフレンズ
        ///0004000000031E00	A66J	戦国無双 Chronicle
        ///0004000000032A00	ABBJ	とびだす!パズルボブル 3D
        ///0004000000032900	AEEJ	ウイニングイレブン 3DSoccer
        ///0004000000031F00	AKKJ	レイトン教授と奇跡の仮面
        ///0004000000034500	ARBJ	ラビッツ タイム・トラベル
        ///0004000000032800	ARRJ	リッジレーサー3D
        ///0004000000034400	ASCJ	Tom Clancy&apos;s スプリンターセル 3D
        ///0004000000033300	A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3dsgames {
            get {
                return ResourceManager.GetString("_3dsgames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ORAS {
            get {
                object obj = ResourceManager.GetObject("ORAS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XY {
            get {
                object obj = ResourceManager.GetObject("XY", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
