namespace CtrDotNet.Pokemon.Reference
{
	public enum GarcNames
	{
		MoveSprites,
		EncounterData,
		TrainerData,
		TrainerClasses,
		TrainerPokemon,
		MapGrid,
		MapMatrix,
		Wallpapers,
		TitleScreen,
		MaisonPokemonN,
		MaisonTrainerN,
		MaisonPokemonS,
		MaisonTrainerS,
		Moves,
		EggMoves,
		Learnsets,
		Evolutions,
		MegaEvolutions,
		PokemonInfo,
		Items,
		GameText,
		StoryText,
		ZoneData,
		WorldData,
		StaticEncounters,
		ItemPickup
	}
}